ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/bps_hw
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/fw_inc
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include

obj-$(CONFIG_MSM_AIS) += bps_dev.o bps_core.o bps_soc.o
