ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_bus/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_top/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_top
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_bus
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw

obj-$(CONFIG_MSM_AIS) += ais_vfe17x.o
