ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/

obj-$(CONFIG_MSM_AIS) += cam_sensor_io.o cam_sensor_cci_i2c.o cam_sensor_qup_i2c.o cam_sensor_spi.o
