ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr/

obj-$(CONFIG_MSM_AIS) += cam_csid_ppi_dev.o cam_csid_ppi_core.o cam_csid_ppi170.o
obj-$(CONFIG_MSM_AIS) += cam_ife_csid_dev.o cam_ife_csid_soc.o cam_ife_csid_core.o
obj-$(CONFIG_MSM_AIS) += cam_ife_csid17x.o cam_ife_csid_lite17x.o
