ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/

obj-$(CONFIG_MSM_AIS) += cam_tasklet_util.o cam_isp_packet_parser.o
obj-$(CONFIG_MSM_AIS) += irq_controller/
