obj-$(CONFIG_OPLUS_FINGERPRINT) += oplus_fp_common/

### Optical fingerprint sensor
ifneq ($(CONFIG_OPLUS_FINGERPRINT_GOODIX)_$(CONFIG_OPLUS_FINGERPRINT_GOODIX_OPTICAL), _)
obj-y += goodix_optical_fp/
endif
