ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cdm
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/

obj-$(CONFIG_MSM_AIS) += hw_utils/ isp_hw/
obj-$(CONFIG_MSM_AIS) += cam_isp_hw_mgr.o cam_ife_hw_mgr.o

