ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_cdm
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_lrme
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_lrme/lrme_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_cpas/include/

obj-$(CONFIG_SPECTRA_CAMERA) += lrme_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_lrme_dev.o cam_lrme_context.o
