ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/isp/isp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/isp/isp_hw/hw_utils/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/isp/isp_hw/isp_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/icp_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/fw_inc/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/icp_hw_mgr/include/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_icp/icp_hw/a5_hw/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include

obj-$(CONFIG_MSM_AIS) += cam_icp_hw_mgr.o
