ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cdm
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_lrme
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_lrme/lrme_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include/

obj-$(CONFIG_MSM_AIS) += lrme_hw_mgr/
obj-$(CONFIG_MSM_AIS) += cam_lrme_dev.o cam_lrme_context.o
