ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_hyp_intf
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
obj-$(CONFIG_MSM_AIS) += cam_hyp_intf.o
