ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_bus/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_bus
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_top/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/ais_isp/vfe_hw/vfe_top

obj-$(CONFIG_MSM_AIS) += ais_vfe_soc.o ais_vfe_dev.o ais_vfe_core.o
obj-$(CONFIG_MSM_AIS) += vfe17x/