# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
#
# Makefile for the OPLUS Linux Kernel system team specific device drivers.
#

obj-$(CONFIG_OPLUS_FEATURE_OPROJECT)		+= oplus_project/
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO)		+= project_info/
obj-$(CONFIG_OPLUS_FEATURE_QCOM_PMICWD)		+= qcom_pmicwd/
