ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_icp
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_icp/fw_inc
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += icp_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_icp_subdev.o cam_icp_context.o hfi.o
