ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core

obj-$(CONFIG_MSM_AIS) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
