ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sync/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cdm/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cpas/include/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_jpeg/jpeg_hw/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_jpeg/jpeg_hw/include/

obj-$(CONFIG_MSM_AIS) += jpeg_enc_hw/
obj-$(CONFIG_MSM_AIS) += jpeg_dma_hw/
obj-$(CONFIG_MSM_AIS) += cam_jpeg_hw_mgr.o
