ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/ais/cam_cdm/

obj-$(CONFIG_MSM_AIS) += isp_hw_mgr/
obj-$(CONFIG_MSM_AIS) += cam_isp_dev.o cam_isp_context.o
